services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile 
    ports:
      - "80:80"
    env_file:
      - .env

  mysql:
    image: mysql:5.7 
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql 


volumes:
  mysql_data: 
